/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchesMatchIdRouteImport } from './routes/matches.$matchId'
import { Route as BroadcasterBroadcasterRouteImport } from './routes/broadcaster.$broadcaster'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesMatchIdRoute = MatchesMatchIdRouteImport.update({
  id: '/matches/$matchId',
  path: '/matches/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const BroadcasterBroadcasterRoute = BroadcasterBroadcasterRouteImport.update({
  id: '/broadcaster/$broadcaster',
  path: '/broadcaster/$broadcaster',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/broadcaster/$broadcaster': typeof BroadcasterBroadcasterRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/broadcaster/$broadcaster': typeof BroadcasterBroadcasterRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/broadcaster/$broadcaster': typeof BroadcasterBroadcasterRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/broadcaster/$broadcaster' | '/matches/$matchId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/broadcaster/$broadcaster' | '/matches/$matchId'
  id: '__root__' | '/' | '/broadcaster/$broadcaster' | '/matches/$matchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BroadcasterBroadcasterRoute: typeof BroadcasterBroadcasterRoute
  MatchesMatchIdRoute: typeof MatchesMatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$matchId': {
      id: '/matches/$matchId'
      path: '/matches/$matchId'
      fullPath: '/matches/$matchId'
      preLoaderRoute: typeof MatchesMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broadcaster/$broadcaster': {
      id: '/broadcaster/$broadcaster'
      path: '/broadcaster/$broadcaster'
      fullPath: '/broadcaster/$broadcaster'
      preLoaderRoute: typeof BroadcasterBroadcasterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BroadcasterBroadcasterRoute: BroadcasterBroadcasterRoute,
  MatchesMatchIdRoute: MatchesMatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
